In [8]:
import torch

C = 3                   # число каналов
H, W = 16, 16           # размеры изображения: H - число строк; W - число столбцов
kernel_size = (3, 3)    # размер ядра по осям (H, W)
stride = (1, 1)         # шаг смещения ядра по осям (H, W)
padding = 0             # размер нулевой области вокруг изображения (число строк и столбцов с каждой стороны)

H_out = int((H + 2 * padding - kernel_size[0]) / stride[0] + 1)
W_out = int((W + 2 * padding - kernel_size[1]) / stride[1] + 1)

x_img = torch.randint(0, 255, (C, H, W), dtype=torch.float32) # тензоры x_img и kernel
kernel = torch.rand((C, ) + kernel_size) # в программе не менять

predict = torch.empty(H_out, W_out, dtype=torch.float32)

# здесь продолжайте программу
for i in range(0, H_out):
    for j in range(0, W_out):
        predict[i, j] = torch.sum(x_img[:, i*stride[0]:kernel_size[0]+i*stride[0], j*stride[1]:kernel_size[1]+j*stride[1]] * kernel)

predict

tensor([[1439.3340, 1519.7229, 1459.1361, 1250.4718, 1516.3859, 1647.2539,
         1602.7433, 1437.3130, 1371.3138, 1381.6514, 1346.2141, 1494.9729,
         1410.0978, 1498.2454],
        [1395.0626, 1348.1752, 1530.2511, 1403.2296, 1605.0566, 1520.1635,
         1685.7446, 1817.5696, 1659.0010, 1976.1376, 1874.8890, 1604.6204,
         1395.2512, 1660.8528],
        [1628.9893, 1398.1970, 1441.2186, 1672.7627, 2008.6272, 1886.6184,
         1671.3931, 2085.0930, 2062.4343, 1866.1426, 1883.0005, 1640.9845,
         1274.3789, 1388.7629],
        [1582.6665, 1774.7218, 1567.3224, 1852.8939, 1636.3224, 1723.3500,
         1817.0879, 1628.4430, 1922.5802, 1763.0425, 1430.7942, 1586.9557,
         1479.2085, 1735.1506],
        [1659.6572, 1872.2324, 1682.2872, 1451.6904, 1620.5208, 1518.3392,
         1582.3662, 1630.7725, 1514.5599, 1310.1223, 1321.8014, 1531.2542,
         1585.2092, 1566.9473],
        [1655.5981, 1913.8054, 1802.2815, 1240.4683, 1569.9352, 1763.0977,
         1915.4

In [3]:
import torch

C = 2                   # число каналов
H, W = 16, 12           # размеры изображения: H - число строк; W - число столбцов
kernel_size = (5, 3)    # размер ядра по осям (H, W)
stride = (1, 1)         # шаг смещения ядра по осям (H, W)
padding = 1             # размер нулевой области вокруг изображения (число строк и столбцов с каждой стороны)

H_out = int((H + 2 * padding - kernel_size[0]) / stride[0] + 1)
W_out = int((W + 2 * padding - kernel_size[1]) / stride[1] + 1)

x_img = torch.randint(0, 255, (C, H, W), dtype=torch.float32) # тензоры x_img и kernel
kernel = torch.rand((C, ) + kernel_size) # в программе не менять

# здесь продолжайте программу
x_img_p = torch.zeros((C, H + 2 * padding, W + 2 * padding))
x_img_p[:, padding:H+padding, padding:W+padding] = x_img

predict = torch.empty(H_out, W_out, dtype=torch.float32)

for i in range(0, H_out):
    for j in range(0, W_out):
        patch = x_img_p[:, i*stride[0]:kernel_size[0]+i*stride[0], j*stride[1]:kernel_size[1]+j*stride[1]]
        predict[i, j] = torch.sum(patch * kernel)

predict

tensor([[ 938.9724, 1317.2703, 1332.7192, 1323.2733, 1338.2654, 1354.4186,
         1637.3774, 1448.0663, 1094.6576, 1070.0784, 1264.4749,  989.4709],
        [1217.8510, 1817.6497, 1860.2084, 1699.1603, 1836.4448, 1905.6499,
         1840.7397, 1899.6459, 1617.0082, 1334.4904, 1437.5297, 1213.2458],
        [1245.6855, 1530.9781, 1540.2693, 1662.2491, 2085.3728, 1918.9353,
         2217.6306, 1837.7271, 1566.6984, 1578.7689, 2050.0037, 1344.5122],
        [1183.1848, 1748.5543, 1763.4437, 1397.2733, 1582.7803, 1897.7397,
         2019.4844, 2053.7495, 1443.2649, 1337.5222, 1695.3018, 1208.1135],
        [1436.9949, 2050.0806, 2000.8494, 1584.8873, 1684.9458, 1572.6001,
         1815.2014, 1774.9829, 1770.5656, 1455.3164, 1609.3530, 1201.9183],
        [1327.7848, 2040.8284, 1947.2955, 1695.5085, 1615.7635, 1847.0934,
         1721.3303, 1858.0925, 1716.7808, 1506.9088, 1613.0323,  986.9970],
        [1123.0250, 1878.3745, 2024.1992, 1666.0068, 1562.8717, 1713.2335,
         1543.5652,

In [9]:
import torch

C = 3                   # число каналов
H, W = 16, 12           # размеры изображения: H - число строк; W - число столбцов
kernel_size = (5, 3)    # размер ядра по осям (H, W)
stride = (1, 2)         # шаг смещения ядра по осям (H, W)
padding = 1             # размер нулевой области вокруг изображения (число строк и столбцов с каждой стороны)

bias = torch.rand(1)    # смещение для фильтра (ядра), коэффициент w0
act = torch.tanh        # функция активации нейронов (результатов свертки)

H_out = int((H + 2 * padding - kernel_size[0]) / stride[0] + 1)
W_out = int((W + 2 * padding - kernel_size[1]) / stride[1] + 1)

x_img = torch.randint(0, 255, (C, H, W), dtype=torch.float32) # тензоры x_img и kernel
kernel = torch.rand((C, ) + kernel_size) # в программе не менять

# здесь продолжайте программу
x_img_p = torch.zeros((C, H + 2 * padding, W + 2 * padding))
x_img_p[:, padding:H+padding, padding:W+padding] = x_img

predict = torch.empty(H_out, W_out, dtype=torch.float32)

for i in range(0, H_out):
    for j in range(0, W_out):
        patch = x_img_p[:, i*stride[0]:i*stride[0]+kernel_size[0], j*stride[1]:j*stride[1]+kernel_size[1]]
        predict[i, j] = act(torch.sum(patch * kernel) + bias)

predict

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
import torch

H, W = 16, 12           # размеры карты признаков: H - число строк; W - число столбцов
kernel_size = (2, 2)    # размер окна для Pooling по осям (H, W)
stride = (2, 2)         # шаг смещения окна по осям (H, W)
padding = 0             # размер нулевой области вокруг карты признаков (число строк и столбцов с каждой стороны)

H_out = int((H + 2 * padding - kernel_size[0]) / stride[0] + 1)
W_out = int((W + 2 * padding - kernel_size[1]) / stride[1] + 1)

x = torch.rand((H, W)) # карта признаков (в программе не менять)

# здесь продолжайте программу
res_pool = torch.empty((H_out, W_out), dtype=torch.float32)

for i in range(0, H_out):
    for j in range(0, W_out):
        res_pool[i, j] = torch.max(x[i*stride[0]:i*stride[0]+kernel_size[0], j*stride[1]:j*stride[1]+kernel_size[1]])

res_pool

tensor([[0.9528, 0.8613, 0.4670, 0.7563, 0.9247, 0.8845],
        [0.8447, 0.8929, 0.9671, 0.7673, 0.7758, 0.6648],
        [0.9615, 0.8153, 0.8558, 0.9217, 0.8215, 0.8363],
        [0.9880, 0.8348, 0.8015, 0.8746, 0.9923, 0.9343],
        [0.8634, 0.9941, 0.6184, 0.8413, 0.9186, 0.9210],
        [0.8802, 0.4872, 0.9832, 0.8580, 0.9174, 0.5439],
        [0.7744, 0.8700, 0.5020, 0.9754, 0.6428, 0.9517],
        [0.5953, 0.3863, 0.8496, 0.9253, 0.8023, 0.9670]])

In [25]:
import torch

H, W = 24, 24           # размеры карты признаков: H - число строк; W - число столбцов
kernel_size = (3, 2)    # размер окна для Pooling по осям (H, W)
stride = (2, 2)         # шаг смещения окна по осям (H, W)
padding = 1             # размер нулевой области вокруг карты признаков (число строк и столбцов с каждой стороны)

H_out = int((H + 2 * padding - kernel_size[0]) / stride[0] + 1)
W_out = int((W + 2 * padding - kernel_size[1]) / stride[1] + 1)

x = torch.rand((H, W)) # карта признаков (в программе не менять)

# здесь продолжайте программу
x_p = torch.zeros((H + 2*padding, W + 2*padding))
x_p[padding:padding+H, padding:padding+W] = x

res_pool = torch.empty(H_out, W_out, dtype=torch.float32)

for i in range(0, H_out):
    for j in range(0, W_out):
        patch = x_p[i*stride[0]:i*stride[0]+kernel_size[0], j*stride[1]:j*stride[1]+kernel_size[1]]
        res_pool[i, j] = torch.mean(patch)

res_pool

tensor([[0.1224, 0.3706, 0.5284, 0.3289, 0.2032, 0.1798, 0.2427, 0.3944, 0.2819,
         0.2596, 0.1635, 0.3734, 0.2641],
        [0.1644, 0.3648, 0.6102, 0.4268, 0.4292, 0.3943, 0.4715, 0.6787, 0.5259,
         0.5624, 0.3171, 0.6463, 0.2999],
        [0.2259, 0.2836, 0.4232, 0.3455, 0.5461, 0.3513, 0.4872, 0.7002, 0.6139,
         0.6563, 0.4087, 0.3714, 0.0923],
        [0.2550, 0.4798, 0.3192, 0.2665, 0.4479, 0.6505, 0.4901, 0.5617, 0.7406,
         0.4403, 0.2093, 0.4072, 0.2605],
        [0.1531, 0.5359, 0.4787, 0.5364, 0.5116, 0.5124, 0.6675, 0.6236, 0.6764,
         0.3007, 0.2527, 0.4701, 0.3796],
        [0.2972, 0.4701, 0.4267, 0.7423, 0.5697, 0.5576, 0.5602, 0.3805, 0.5615,
         0.5003, 0.6809, 0.4868, 0.2777],
        [0.3308, 0.4456, 0.5352, 0.5341, 0.5006, 0.5569, 0.6862, 0.4375, 0.5495,
         0.5445, 0.4336, 0.5758, 0.3168],
        [0.1675, 0.4004, 0.4544, 0.4606, 0.4548, 0.4913, 0.8220, 0.4815, 0.3655,
         0.4841, 0.4554, 0.4840, 0.1306],
        [0.1979,